default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: 123456
  port: 5432
  encoding: UTF8

development:
  <<: *default
  database: kiwi_frult_dev
test:
  <<: *default
  database: kiwi_frult_test
production:
  <<: *default
  database: kiwi_frult_production

